spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
#  default-produces-media-type: application/json
#  default-consumes-media-type: application/json